tomcat:
  ajp:
    enabled: true
    port: 8009
    address: 0.0.0.0
    remoteauthentication: false

security:
  jmx:
    enabled: true

management:
  endpoints:
    web.exposure.include: '*'
  endpoint:
    health.show-details: always
    jolokia:
      enabled: true
      access:
        admin:  # csak admin jogosultságú felhasználóknak
          roles: "ROLE_ADMIN"
        execute:
          roles: "ROLE_ADMIN"
    env.show-values: ALWAYS

spring:
  jmx.unique-names: true
  security:
    user:
      name: admin
      password: secret123
      roles: ADMIN
  boot.admin.client:
    url: http://localhost:8888/admin
    username: root
    password: secret
    instance:
      metadata:
        user:
          name: ${spring.security.user.name}
          password: ${spring.security.user.password}

management.endpoints.jmx.domain: com.github.dobrosi.demo

test:
  value: 7
